newIssueWelcomeComment: >
  感谢你提交的问题或反馈，我会尽快回复，在此期间你可以看看[之前被解决的反馈](https://github.com/funnyzak/tts-now/issues?q=is%3Aissue+is%3Aclosed)说不定有你需要的答案。
  
  Thanks for opening this issue, a maintainer will get back to you shortly!
  
newPRWelcomeComment: >
  感谢你提交的问题或反馈，我会尽快来审查代码。
  
  Thanks so much for opening your first PR here!
firstPRMergeComment: >
  感谢贡献 PR 来支持 Funnyzak! :tada:
  
  Congrats on merging your first pull request here! :tada: How awesome!